# Dev shell + pre-commit hooks via dryvist/nix-devenv flakeModules.
#
# Replaces the previous Pattern-B `.envrc` remote-shell setup with a
# local flake that imports nix-devenv.flakeModules.ansible. The ansible
# profile composes the base hygiene hooks (file checks, markdownlint,
# zizmor, treefmt, deadnix, statix, gitleaks-via-base-once-added) with
# ansible-lint and yamllint, both reading canonical configs from
# dryvist/.github via nix-devenv.lib.fetch-shared-configs.
#
# Per-repo overrides kept inline below.
{
  description = "Proxmox VE host configuration via Ansible.";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-25.11-darwin";
    flake-parts.url = "github:hercules-ci/flake-parts";
    nix-devenv = {
      url = "github:dryvist/nix-devenv";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    inputs@{
      flake-parts,
      nix-devenv,
      ...
    }:
    flake-parts.lib.mkFlake { inherit inputs; } {
      systems = [
        "aarch64-darwin"
        "x86_64-darwin"
        "x86_64-linux"
        "aarch64-linux"
      ];

      imports = [ nix-devenv.flakeModules.ansible ];

      perSystem =
        {
          pkgs,
          system,
          ...
        }:
        {
          devShells.default = nix-devenv.devShells.${system}.ansible;

          # Files regenerated by other tooling or vendored from upstream —
          # treefmt would create churn loops or diverge from upstream.
          treefmt.settings.global.excludes = [
            ".github/workflows/*.lock.yml"
            ".github/aw/imports/**"
            "CHANGELOG.md"
          ];

          pre-commit.settings.hooks = {
            # gitleaks not yet in cachix/git-hooks.nix's supported set;
            # wire manually until it lands in the base profile.
            gitleaks = {
              enable = true;
              name = "gitleaks";
              entry = "${pkgs.gitleaks}/bin/gitleaks protect --verbose --redact --staged";
              language = "system";
              pass_filenames = false;
            };

            # gh-aw compiled workflows + vendored gh-aw imports carry
            # intentional trailing whitespace, EOF, and document-start
            # formatting from the generator; the base hygiene hooks and
            # yamllint would rewrite/complain only for `gh-aw compile`
            # to revert on the next pass. yamllint also enforces
            # `document-start: enable` from its `extends: default`, and
            # GitHub Actions workflows by convention start with `name:`
            # not `---`, so exclude all workflow YAML from yamllint
            # entirely (the workflows are linted by zizmor instead).
            trim-trailing-whitespace.excludes = [ "^(\\.github/workflows/.*\\.lock\\.yml|\\.github/aw/)" ];
            end-of-file-fixer.excludes = [ "^(\\.github/workflows/.*\\.lock\\.yml|\\.github/aw/)" ];
            yamllint.excludes = [ "^(\\.github/workflows/.*\\.ya?ml|\\.github/aw/)" ];
          };
        };
    };
}
