---
platforms:
  - name: proxmox-nvidia-driver-test
    image: "${MOLECULE_IMAGE:-debian:stable-slim}"
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /tmp

driver:
  name: docker

provisioner:
  config_options:
    defaults:
      roles_path: ${MOLECULE_SCENARIO_DIRECTORY}/../../roles
