---
platforms:
  - name: pve-guest-evacuation-lxc-managed-volumes-test
    image: "${MOLECULE_IMAGE:-geerlingguy/docker-debian12-ansible:latest}"
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /tmp
provisioner:
  config_options:
    defaults:
      roles_path: ${MOLECULE_SCENARIO_DIRECTORY}/../../roles
