---
platforms:
  - name: proxmox-nas-test
    image: "${MOLECULE_IMAGE:-debian:stable-slim}"
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /tmp

provisioner:
  env:
    NAS_HOMEASSISTANT_SMB_PASSWORD: molecule-pass
