---
platforms:
  - name: proxmox-syncoid-test
    image: "${MOLECULE_IMAGE:-geerlingguy/docker-debian12-ansible:latest}"
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /tmp
