---
platforms:
  - name: proxmox-test
    image: "${MOLECULE_IMAGE:-debian:stable-slim}"
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /tmp

provisioner:
  inventory:
    group_vars:
      all:
        # Override defaults for testing environment
        zfs_swap_size: "1G"
        common_packages:
          - htop
